up:
	sudo docker compose -p spottier -f docker/docker-compose.yaml up -d
build:
	sudo docker compose -p spottier -f docker/docker-compose.yaml up -d --build
down:
	sudo docker compose -p spottier -f docker/docker-compose.yaml stop
status:
	sudo docker ps --all --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"